on:
  workflow_call:
    inputs:
      ssh_host:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      project_path:
        required: true
        type: string
    secrets:
      SSH_PASSWORD:
        required: true

jobs:
  pull-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Build on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_user }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ inputs.project_path }}
            echo "Pulling latest code..."
            git pull origin dev

            echo "Backing up existing build"
            [ -d dist ] && mv dist dist_prev || echo "No existing dist folder"

            echo "Installing dependencies and building project..."
            npm ci
            npm run build

            echo "Reloading nginx"
            sudo systemctl reload nginx
